
!
hostname leaf_router_2_4
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65224
 bgp router-id 172.16.2.9
 no bgp ebgp-requires-policy
 network 10.2.4.0/24
 neighbor 172.16.2.8 remote-as 65120
 neighbor 172.16.2.24 remote-as 65121
 neighbor 172.16.2.40 remote-as 65122
 neighbor 172.16.2.56 remote-as 65123
 neighbor 172.16.2.72 remote-as 65124
 neighbor 172.16.2.88 remote-as 65125
 neighbor 172.16.2.104 remote-as 65126
 neighbor 172.16.2.120 remote-as 65127
!
line vty
