[Interface]
Address = 172.16.1.1/24
ListenPort = 51820
PrivateKey = KPEyzEsooRs7i7DG49MPbPfJtoF/8lIBPYov8yJltkQ=

# host_1
[Peer]
PublicKey = 6XeD4elvrP1lBENFdTLyl39boqqSS3E50y4En4UJKXg=
AllowedIPs = 172.16.1.11/32

# web_server_1_1
[Peer]
PublicKey = HR07FtBxWi0cNDvZC6/GKRkL1IzCJ+7NQDQBUMR2JXk=
AllowedIPs = 172.16.1.21/32

# web_server_1_2
[Peer]
PublicKey = aqQjDoAVpl2uSODMc5mmpBTCJ+P4ihOwMs7yMwMe1nI=
AllowedIPs = 172.16.1.22/32