
!
hostname leaf_router_3_7
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65237
 bgp router-id 172.16.2.143
 no bgp ebgp-requires-policy
 network 10.3.7.0/24
 neighbor 172.16.2.142 remote-as 65130
 neighbor 172.16.2.158 remote-as 65131
 neighbor 172.16.2.174 remote-as 65132
 neighbor 172.16.2.190 remote-as 65133
 neighbor 172.16.2.206 remote-as 65134
 neighbor 172.16.2.222 remote-as 65135
 neighbor 172.16.2.238 remote-as 65136
 neighbor 172.16.2.254 remote-as 65137
!
line vty
