
!
hostname leaf_router_2_6
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65226
 bgp router-id 172.16.1.13
 bgp bestpath as-path multipath-relax
 maximum-paths 32
 no bgp ebgp-requires-policy
 network 10.2.6.0/24
 neighbor 172.16.1.12 remote-as 65120
 neighbor 172.16.1.28 remote-as 65121
 neighbor 172.16.1.44 remote-as 65122
 neighbor 172.16.1.60 remote-as 65123
!
line vty
