
!
hostname leaf_router_0_2
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65202
 bgp router-id 172.16.0.133
 bgp bestpath as-path multipath-relax
 maximum-paths 32
 no bgp ebgp-requires-policy
 network 10.0.2.0/24
 neighbor 172.16.0.132 remote-as 65100
 neighbor 172.16.0.148 remote-as 65101
 neighbor 172.16.0.164 remote-as 65102
 neighbor 172.16.0.180 remote-as 65103
!
line vty
