
!
hostname leaf_router_2_6
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65226
 bgp router-id 172.16.2.13
 no bgp ebgp-requires-policy
 network 10.2.6.0/24
 neighbor 172.16.2.12 remote-as 65120
 neighbor 172.16.2.28 remote-as 65121
 neighbor 172.16.2.44 remote-as 65122
 neighbor 172.16.2.60 remote-as 65123
 neighbor 172.16.2.76 remote-as 65124
 neighbor 172.16.2.92 remote-as 65125
 neighbor 172.16.2.108 remote-as 65126
 neighbor 172.16.2.124 remote-as 65127
!
line vty
