LAB_NAME="sdn_star"
LAB_DESCRIPTION="SDN star topology"

switch_0[0]="switch_0_switch_1"
switch_0[1]="switch_0_switch_2"
switch_0[2]="switch_0_switch_3"
switch_0[3]="switch_0_switch_4"
switch_0[4]="switch_0_switch_5"
switch_0[5]="switch_0_switch_6"
switch_0[6]="switch_0_switch_7"
switch_0[7]="switch_0_switch_8"
switch_0[8]="switch_controller"
switch_0[image]="kathara/sdn"
switch_0[cpus]=0.5
switch_0[mem]="256m"

switch_1[0]="host_1_switch_1"
switch_1[1]="switch_0_switch_1"
switch_1[2]="switch_controller"
switch_1[image]="kathara/sdn"
switch_1[cpus]=0.5
switch_1[mem]="256m"

switch_2[0]="host_2_switch_2"
switch_2[1]="switch_0_switch_2"
switch_2[2]="switch_controller"
switch_2[image]="kathara/sdn"
switch_2[cpus]=0.5
switch_2[mem]="256m"

switch_3[0]="host_3_switch_3"
switch_3[1]="switch_0_switch_3"
switch_3[2]="switch_controller"
switch_3[image]="kathara/sdn"
switch_3[cpus]=0.5
switch_3[mem]="256m"

switch_4[0]="host_4_switch_4"
switch_4[1]="switch_0_switch_4"
switch_4[2]="switch_controller"
switch_4[image]="kathara/sdn"
switch_4[cpus]=0.5
switch_4[mem]="256m"

switch_5[0]="host_5_switch_5"
switch_5[1]="switch_0_switch_5"
switch_5[2]="switch_controller"
switch_5[image]="kathara/sdn"
switch_5[cpus]=0.5
switch_5[mem]="256m"

switch_6[0]="host_6_switch_6"
switch_6[1]="switch_0_switch_6"
switch_6[2]="switch_controller"
switch_6[image]="kathara/sdn"
switch_6[cpus]=0.5
switch_6[mem]="256m"

switch_7[0]="host_7_switch_7"
switch_7[1]="switch_0_switch_7"
switch_7[2]="switch_controller"
switch_7[image]="kathara/sdn"
switch_7[cpus]=0.5
switch_7[mem]="256m"

switch_8[0]="host_8_switch_8"
switch_8[1]="switch_0_switch_8"
switch_8[2]="switch_controller"
switch_8[image]="kathara/sdn"
switch_8[cpus]=0.5
switch_8[mem]="256m"

host_1[0]="host_1_switch_1"
host_1[image]="kathara/nika-base"
host_1[cpus]=0.5
host_1[mem]="256m"

host_2[0]="host_2_switch_2"
host_2[image]="kathara/nika-base"
host_2[cpus]=0.5
host_2[mem]="256m"

host_3[0]="host_3_switch_3"
host_3[image]="kathara/nika-base"
host_3[cpus]=0.5
host_3[mem]="256m"

host_4[0]="host_4_switch_4"
host_4[image]="kathara/nika-base"
host_4[cpus]=0.5
host_4[mem]="256m"

host_5[0]="host_5_switch_5"
host_5[image]="kathara/nika-base"
host_5[cpus]=0.5
host_5[mem]="256m"

host_6[0]="host_6_switch_6"
host_6[image]="kathara/nika-base"
host_6[cpus]=0.5
host_6[mem]="256m"

host_7[0]="host_7_switch_7"
host_7[image]="kathara/nika-base"
host_7[cpus]=0.5
host_7[mem]="256m"

host_8[0]="host_8_switch_8"
host_8[image]="kathara/nika-base"
host_8[cpus]=0.5
host_8[mem]="256m"

controller[0]="switch_controller"
controller[image]="kathara/nika-ryu"
controller[cpus]=0.5
controller[mem]="256m"
controller[bridged]=true
