LAB_NAME="campus_static"
LAB_DESCRIPTION="OSPF Enterprise Static"

router_core_1[0]="router_core_1_router_core_2"
router_core_1[1]="router_core_1_router_core_3"
router_core_1[2]="router_core_1_switch_dist_1_1"
router_core_1[image]="kathara/nika-frr"
router_core_1[cpus]=0.5
router_core_1[mem]="256m"

router_core_2[0]="router_core_1_router_core_2"
router_core_2[1]="router_core_2_router_core_3"
router_core_2[2]="router_core_2_switch_dist_2_1"
router_core_2[image]="kathara/nika-frr"
router_core_2[cpus]=0.5
router_core_2[mem]="256m"

router_core_3[0]="router_core_1_router_core_3"
router_core_3[1]="router_core_2_router_core_3"
router_core_3[2]="router_core_3_switch_server_access"
router_core_3[image]="kathara/nika-frr"
router_core_3[cpus]=0.5
router_core_3[mem]="256m"

switch_dist_1_1[0]="router_core_1_switch_dist_1_1"
switch_dist_1_1[1]="switch_dist_1_1_switch_access_1_1_1"
switch_dist_1_1[image]="kathara/nika-frr"
switch_dist_1_1[cpus]=0.5
switch_dist_1_1[mem]="256m"

switch_dist_2_1[0]="router_core_2_switch_dist_2_1"
switch_dist_2_1[1]="switch_dist_2_1_switch_access_2_1_1"
switch_dist_2_1[image]="kathara/nika-frr"
switch_dist_2_1[cpus]=0.5
switch_dist_2_1[mem]="256m"

switch_server_access[0]="switch_server_access_dns_server"
switch_server_access[1]="switch_server_access_web_server_0"
switch_server_access[2]="switch_server_access_web_server_1"
switch_server_access[3]="switch_server_access_web_server_2"
switch_server_access[4]="switch_server_access_web_server_3"
switch_server_access[5]="router_core_3_switch_server_access"
switch_server_access[image]="kathara/nika-frr"
switch_server_access[cpus]=0.5
switch_server_access[mem]="256m"

switch_access_1_1_1[0]="switch_dist_1_1_switch_access_1_1_1"
switch_access_1_1_1[1]="switch_access_1_1_1_host_1_1_1_1"
switch_access_1_1_1[image]="kathara/nika-base"
switch_access_1_1_1[cpus]=0.5
switch_access_1_1_1[mem]="256m"

switch_access_2_1_1[0]="switch_dist_2_1_switch_access_2_1_1"
switch_access_2_1_1[1]="switch_access_2_1_1_host_2_1_1_1"
switch_access_2_1_1[image]="kathara/nika-base"
switch_access_2_1_1[cpus]=0.5
switch_access_2_1_1[mem]="256m"

host_1_1_1_1[0]="switch_access_1_1_1_host_1_1_1_1"
host_1_1_1_1[image]="kathara/nika-base"
host_1_1_1_1[cpus]=0.5
host_1_1_1_1[mem]="256m"

host_2_1_1_1[0]="switch_access_2_1_1_host_2_1_1_1"
host_2_1_1_1[image]="kathara/nika-base"
host_2_1_1_1[cpus]=0.5
host_2_1_1_1[mem]="256m"

dns_server[0]="switch_server_access_dns_server"
dns_server[image]="kathara/nika-base"
dns_server[cpus]=0.5
dns_server[mem]="256m"

web_server_0[0]="switch_server_access_web_server_0"
web_server_0[image]="kathara/nika-base"
web_server_0[cpus]=0.5
web_server_0[mem]="256m"

web_server_1[0]="switch_server_access_web_server_1"
web_server_1[image]="kathara/nika-base"
web_server_1[cpus]=0.5
web_server_1[mem]="256m"

web_server_2[0]="switch_server_access_web_server_2"
web_server_2[image]="kathara/nika-base"
web_server_2[cpus]=0.5
web_server_2[mem]="256m"

web_server_3[0]="switch_server_access_web_server_3"
web_server_3[image]="kathara/nika-base"
web_server_3[cpus]=0.5
web_server_3[mem]="256m"
