LAB_NAME="sdn_clos"
LAB_DESCRIPTION="SDN Clos topology"

spine_1[0]="spine_1_leaf_1"
spine_1[1]="spine_1_leaf_2"
spine_1[2]="spine_1_leaf_3"
spine_1[3]="spine_1_leaf_4"
spine_1[4]="switch_controller"
spine_1[image]="kathara/sdn"
spine_1[cpus]=0.5
spine_1[mem]="256m"

spine_2[0]="spine_2_leaf_1"
spine_2[1]="spine_2_leaf_2"
spine_2[2]="spine_2_leaf_3"
spine_2[3]="spine_2_leaf_4"
spine_2[4]="switch_controller"
spine_2[image]="kathara/sdn"
spine_2[cpus]=0.5
spine_2[mem]="256m"

leaf_1[0]="host_1_1_leaf_1"
leaf_1[1]="host_1_2_leaf_1"
leaf_1[2]="host_1_3_leaf_1"
leaf_1[3]="host_1_4_leaf_1"
leaf_1[4]="spine_1_leaf_1"
leaf_1[5]="spine_2_leaf_1"
leaf_1[6]="switch_controller"
leaf_1[image]="kathara/sdn"
leaf_1[cpus]=0.5
leaf_1[mem]="256m"

leaf_2[0]="host_2_1_leaf_2"
leaf_2[1]="host_2_2_leaf_2"
leaf_2[2]="host_2_3_leaf_2"
leaf_2[3]="host_2_4_leaf_2"
leaf_2[4]="spine_1_leaf_2"
leaf_2[5]="spine_2_leaf_2"
leaf_2[6]="switch_controller"
leaf_2[image]="kathara/sdn"
leaf_2[cpus]=0.5
leaf_2[mem]="256m"

leaf_3[0]="host_3_1_leaf_3"
leaf_3[1]="host_3_2_leaf_3"
leaf_3[2]="host_3_3_leaf_3"
leaf_3[3]="host_3_4_leaf_3"
leaf_3[4]="spine_1_leaf_3"
leaf_3[5]="spine_2_leaf_3"
leaf_3[6]="switch_controller"
leaf_3[image]="kathara/sdn"
leaf_3[cpus]=0.5
leaf_3[mem]="256m"

leaf_4[0]="host_4_1_leaf_4"
leaf_4[1]="host_4_2_leaf_4"
leaf_4[2]="host_4_3_leaf_4"
leaf_4[3]="host_4_4_leaf_4"
leaf_4[4]="spine_1_leaf_4"
leaf_4[5]="spine_2_leaf_4"
leaf_4[6]="switch_controller"
leaf_4[image]="kathara/sdn"
leaf_4[cpus]=0.5
leaf_4[mem]="256m"

host_1_1[0]="host_1_1_leaf_1"
host_1_1[image]="kathara/nika-base"
host_1_1[cpus]=0.5
host_1_1[mem]="256m"

host_1_2[0]="host_1_2_leaf_1"
host_1_2[image]="kathara/nika-base"
host_1_2[cpus]=0.5
host_1_2[mem]="256m"

host_1_3[0]="host_1_3_leaf_1"
host_1_3[image]="kathara/nika-base"
host_1_3[cpus]=0.5
host_1_3[mem]="256m"

host_1_4[0]="host_1_4_leaf_1"
host_1_4[image]="kathara/nika-base"
host_1_4[cpus]=0.5
host_1_4[mem]="256m"

host_2_1[0]="host_2_1_leaf_2"
host_2_1[image]="kathara/nika-base"
host_2_1[cpus]=0.5
host_2_1[mem]="256m"

host_2_2[0]="host_2_2_leaf_2"
host_2_2[image]="kathara/nika-base"
host_2_2[cpus]=0.5
host_2_2[mem]="256m"

host_2_3[0]="host_2_3_leaf_2"
host_2_3[image]="kathara/nika-base"
host_2_3[cpus]=0.5
host_2_3[mem]="256m"

host_2_4[0]="host_2_4_leaf_2"
host_2_4[image]="kathara/nika-base"
host_2_4[cpus]=0.5
host_2_4[mem]="256m"

host_3_1[0]="host_3_1_leaf_3"
host_3_1[image]="kathara/nika-base"
host_3_1[cpus]=0.5
host_3_1[mem]="256m"

host_3_2[0]="host_3_2_leaf_3"
host_3_2[image]="kathara/nika-base"
host_3_2[cpus]=0.5
host_3_2[mem]="256m"

host_3_3[0]="host_3_3_leaf_3"
host_3_3[image]="kathara/nika-base"
host_3_3[cpus]=0.5
host_3_3[mem]="256m"

host_3_4[0]="host_3_4_leaf_3"
host_3_4[image]="kathara/nika-base"
host_3_4[cpus]=0.5
host_3_4[mem]="256m"

host_4_1[0]="host_4_1_leaf_4"
host_4_1[image]="kathara/nika-base"
host_4_1[cpus]=0.5
host_4_1[mem]="256m"

host_4_2[0]="host_4_2_leaf_4"
host_4_2[image]="kathara/nika-base"
host_4_2[cpus]=0.5
host_4_2[mem]="256m"

host_4_3[0]="host_4_3_leaf_4"
host_4_3[image]="kathara/nika-base"
host_4_3[cpus]=0.5
host_4_3[mem]="256m"

host_4_4[0]="host_4_4_leaf_4"
host_4_4[image]="kathara/nika-base"
host_4_4[cpus]=0.5
host_4_4[mem]="256m"

controller[0]="switch_controller"
controller[image]="kathara/nika-ryu"
controller[cpus]=0.5
controller[mem]="256m"
controller[bridged]=true
