
!
hostname leaf_router_0_1
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65201
 bgp router-id 172.16.1.3
 no bgp ebgp-requires-policy
 network 10.0.1.0/24
 neighbor 172.16.1.2 remote-as 65100
 neighbor 172.16.1.18 remote-as 65101
 neighbor 172.16.1.34 remote-as 65102
 neighbor 172.16.1.50 remote-as 65103
 neighbor 172.16.1.66 remote-as 65104
 neighbor 172.16.1.82 remote-as 65105
 neighbor 172.16.1.98 remote-as 65106
 neighbor 172.16.1.114 remote-as 65107
!
line vty
