
!
hostname leaf_router_2_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65223
 bgp router-id 172.16.2.7
 no bgp ebgp-requires-policy
 network 10.2.3.0/24
 neighbor 172.16.2.6 remote-as 65120
 neighbor 172.16.2.22 remote-as 65121
 neighbor 172.16.2.38 remote-as 65122
 neighbor 172.16.2.54 remote-as 65123
 neighbor 172.16.2.70 remote-as 65124
 neighbor 172.16.2.86 remote-as 65125
 neighbor 172.16.2.102 remote-as 65126
 neighbor 172.16.2.118 remote-as 65127
!
line vty
