
!
hostname leaf_router_3_1
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65231
 bgp router-id 172.16.2.131
 no bgp ebgp-requires-policy
 network 10.3.1.0/24
 neighbor 172.16.2.130 remote-as 65130
 neighbor 172.16.2.146 remote-as 65131
 neighbor 172.16.2.162 remote-as 65132
 neighbor 172.16.2.178 remote-as 65133
 neighbor 172.16.2.194 remote-as 65134
 neighbor 172.16.2.210 remote-as 65135
 neighbor 172.16.2.226 remote-as 65136
 neighbor 172.16.2.242 remote-as 65137
!
line vty
