LAB_NAME="p4_bloom_filter"
LAB_DESCRIPTION="P4 Bloom Filter - 2 hosts, 2 switches"

host_1[0]="A"
host_1[image]="kathara/base"
host_1[cpus]=0.5
host_1[mem]="256m"

host_2[0]="B"
host_2[image]="kathara/base"
host_2[cpus]=0.5
host_2[mem]="256m"

switch_1[0]="A"
switch_1[1]="C"
switch_1[image]="kathara/p4"
switch_1[cpus]=0.5
switch_1[mem]="256m"

switch_2[0]="B"
switch_2[1]="C"
switch_2[image]="kathara/p4"
switch_2[cpus]=0.5
switch_2[mem]="256m"
