
!
hostname spine_router_0_2
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65102
 bgp router-id 172.16.0.5
 no bgp ebgp-requires-policy
  neighbor 172.16.0.4 remote-as 65000
 neighbor 172.16.0.20 remote-as 65000
 neighbor 172.16.0.49 remote-as 65200
 neighbor 172.16.0.51 remote-as 65201
 neighbor 172.16.0.53 remote-as 65202
 neighbor 172.16.0.55 remote-as 65203
!
line vty
