
!
hostname leaf_router_2_2
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65222
 bgp router-id 172.16.2.5
 no bgp ebgp-requires-policy
 network 10.2.2.0/24
 neighbor 172.16.2.4 remote-as 65120
 neighbor 172.16.2.20 remote-as 65121
 neighbor 172.16.2.36 remote-as 65122
 neighbor 172.16.2.52 remote-as 65123
 neighbor 172.16.2.68 remote-as 65124
 neighbor 172.16.2.84 remote-as 65125
 neighbor 172.16.2.100 remote-as 65126
 neighbor 172.16.2.116 remote-as 65127
!
line vty
