LAB_NAME="dc_clos_service"
LAB_DESCRIPTION="DC Clos BGP topology"

super_spine_router_0[0]="super_spine_router_0_spine_router_0_0"
super_spine_router_0[1]="super_spine_router_0_spine_router_0_1"
super_spine_router_0[2]="super_spine_router_0_client_0"
super_spine_router_0[image]="kathara/nika-frr"
super_spine_router_0[cpus]=0.5
super_spine_router_0[mem]="256m"

spine_router_0_0[0]="super_spine_router_0_spine_router_0_0"
spine_router_0_0[1]="spine_router_0_0_leaf_router_0_0"
spine_router_0_0[2]="spine_router_0_0_leaf_router_0_1"
spine_router_0_0[image]="kathara/nika-frr"
spine_router_0_0[cpus]=0.5
spine_router_0_0[mem]="256m"

spine_router_0_1[0]="super_spine_router_0_spine_router_0_1"
spine_router_0_1[1]="spine_router_0_1_leaf_router_0_0"
spine_router_0_1[2]="spine_router_0_1_leaf_router_0_1"
spine_router_0_1[image]="kathara/nika-frr"
spine_router_0_1[cpus]=0.5
spine_router_0_1[mem]="256m"

leaf_router_0_0[0]="spine_router_0_0_leaf_router_0_0"
leaf_router_0_0[1]="spine_router_0_1_leaf_router_0_0"
leaf_router_0_0[2]="leaf_router_0_0_dns_pod0"
leaf_router_0_0[image]="kathara/nika-frr"
leaf_router_0_0[cpus]=0.5
leaf_router_0_0[mem]="256m"

leaf_router_0_1[0]="spine_router_0_0_leaf_router_0_1"
leaf_router_0_1[1]="spine_router_0_1_leaf_router_0_1"
leaf_router_0_1[2]="leaf_router_0_1_webserver0_pod0"
leaf_router_0_1[image]="kathara/nika-frr"
leaf_router_0_1[cpus]=0.5
leaf_router_0_1[mem]="256m"

dns_pod0[0]="leaf_router_0_0_dns_pod0"
dns_pod0[image]="kathara/nika-base"
dns_pod0[cpus]=0.5
dns_pod0[mem]="256m"

webserver0_pod0[0]="leaf_router_0_1_webserver0_pod0"
webserver0_pod0[image]="kathara/nika-base"
webserver0_pod0[cpus]=0.5
webserver0_pod0[mem]="256m"

client_0[0]="super_spine_router_0_client_0"
client_0[image]="kathara/nika-base"
client_0[cpus]=0.5
client_0[mem]="256m"
