
!
hostname leaf_router_2_1
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65221
 bgp router-id 172.16.2.3
 no bgp ebgp-requires-policy
 network 10.2.1.0/24
 neighbor 172.16.2.2 remote-as 65120
 neighbor 172.16.2.18 remote-as 65121
 neighbor 172.16.2.34 remote-as 65122
 neighbor 172.16.2.50 remote-as 65123
 neighbor 172.16.2.66 remote-as 65124
 neighbor 172.16.2.82 remote-as 65125
 neighbor 172.16.2.98 remote-as 65126
 neighbor 172.16.2.114 remote-as 65127
!
line vty
