
!
hostname spine_router_0_1
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65101
 bgp router-id 172.16.0.3
 bgp bestpath as-path multipath-relax
 maximum-paths 32
 no bgp ebgp-requires-policy
  neighbor 172.16.0.2 remote-as 65000
 neighbor 172.16.0.34 remote-as 65000
 neighbor 172.16.0.66 remote-as 65000
 neighbor 172.16.0.98 remote-as 65000
 neighbor 172.16.0.145 remote-as 65200
 neighbor 172.16.0.147 remote-as 65201
 neighbor 172.16.0.149 remote-as 65202
 neighbor 172.16.0.151 remote-as 65203
 neighbor 172.16.0.153 remote-as 65204
 neighbor 172.16.0.155 remote-as 65205
 neighbor 172.16.0.157 remote-as 65206
 neighbor 172.16.0.159 remote-as 65207
!
line vty
