
!
hostname spine_router_1_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65113
 bgp router-id 172.16.0.15
 no bgp ebgp-requires-policy
  neighbor 172.16.0.14 remote-as 65000
 neighbor 172.16.0.30 remote-as 65000
 neighbor 172.16.0.89 remote-as 65210
 neighbor 172.16.0.91 remote-as 65211
 neighbor 172.16.0.93 remote-as 65212
 neighbor 172.16.0.95 remote-as 65213
!
line vty
