
!
hostname leaf_router_2_7
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65227
 bgp router-id 172.16.2.15
 no bgp ebgp-requires-policy
 network 10.2.7.0/24
 neighbor 172.16.2.14 remote-as 65120
 neighbor 172.16.2.30 remote-as 65121
 neighbor 172.16.2.46 remote-as 65122
 neighbor 172.16.2.62 remote-as 65123
 neighbor 172.16.2.78 remote-as 65124
 neighbor 172.16.2.94 remote-as 65125
 neighbor 172.16.2.110 remote-as 65126
 neighbor 172.16.2.126 remote-as 65127
!
line vty
