
!
hostname leaf_router_2_5
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65225
 bgp router-id 172.16.2.11
 no bgp ebgp-requires-policy
 network 10.2.5.0/24
 neighbor 172.16.2.10 remote-as 65120
 neighbor 172.16.2.26 remote-as 65121
 neighbor 172.16.2.42 remote-as 65122
 neighbor 172.16.2.58 remote-as 65123
 neighbor 172.16.2.74 remote-as 65124
 neighbor 172.16.2.90 remote-as 65125
 neighbor 172.16.2.106 remote-as 65126
 neighbor 172.16.2.122 remote-as 65127
!
line vty
