LAB_NAME="p4_counter"
LAB_DESCRIPTION="P4 Counter - 3 hosts, 4 switches"

pc1[0]="A"
pc1[image]="kathara/base"
pc1[cpus]=0.5
pc1[mem]="256m"

pc2[0]="F"
pc2[image]="kathara/base"
pc2[cpus]=0.5
pc2[mem]="256m"

pc3[0]="G"
pc3[image]="kathara/base"
pc3[cpus]=0.5
pc3[mem]="256m"

s1[0]="A"
s1[1]="B"
s1[2]="C"
s1[image]="kathara/p4"
s1[cpus]=0.5
s1[mem]="256m"

s2[0]="B"
s2[1]="D"
s2[image]="kathara/p4"
s2[cpus]=0.5
s2[mem]="256m"

s3[0]="C"
s3[1]="E"
s3[image]="kathara/p4"
s3[cpus]=0.5
s3[mem]="256m"

s4[0]="D"
s4[1]="E"
s4[2]="F"
s4[3]="G"
s4[image]="kathara/p4"
s4[cpus]=0.5
s4[mem]="256m"
