
!
hostname spine_router_0_1
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65101
 bgp router-id 172.16.0.3
 no bgp ebgp-requires-policy
  neighbor 172.16.0.2 remote-as 65000
 neighbor 172.16.0.18 remote-as 65000
 neighbor 172.16.0.41 remote-as 65200
 neighbor 172.16.0.43 remote-as 65201
 neighbor 172.16.0.45 remote-as 65202
 neighbor 172.16.0.47 remote-as 65203
!
line vty
