
!
hostname leaf_router_0_6
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65206
 bgp router-id 172.16.1.13
 no bgp ebgp-requires-policy
 network 10.0.6.0/24
 neighbor 172.16.1.12 remote-as 65100
 neighbor 172.16.1.28 remote-as 65101
 neighbor 172.16.1.44 remote-as 65102
 neighbor 172.16.1.60 remote-as 65103
 neighbor 172.16.1.76 remote-as 65104
 neighbor 172.16.1.92 remote-as 65105
 neighbor 172.16.1.108 remote-as 65106
 neighbor 172.16.1.124 remote-as 65107
!
line vty
