
!
hostname leaf_router_1_0
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65210
 bgp router-id 172.16.0.65
 no bgp ebgp-requires-policy
 network 10.1.0.0/24
 neighbor 172.16.0.64 remote-as 65110
 neighbor 172.16.0.72 remote-as 65111
 neighbor 172.16.0.80 remote-as 65112
 neighbor 172.16.0.88 remote-as 65113
!
line vty
