
!
hostname leaf_router_3_4
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65234
 bgp router-id 172.16.2.137
 no bgp ebgp-requires-policy
 network 10.3.4.0/24
 neighbor 172.16.2.136 remote-as 65130
 neighbor 172.16.2.152 remote-as 65131
 neighbor 172.16.2.168 remote-as 65132
 neighbor 172.16.2.184 remote-as 65133
 neighbor 172.16.2.200 remote-as 65134
 neighbor 172.16.2.216 remote-as 65135
 neighbor 172.16.2.232 remote-as 65136
 neighbor 172.16.2.248 remote-as 65137
!
line vty
