
!
hostname leaf_router_3_6
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65236
 bgp router-id 172.16.2.141
 no bgp ebgp-requires-policy
 network 10.3.6.0/24
 neighbor 172.16.2.140 remote-as 65130
 neighbor 172.16.2.156 remote-as 65131
 neighbor 172.16.2.172 remote-as 65132
 neighbor 172.16.2.188 remote-as 65133
 neighbor 172.16.2.204 remote-as 65134
 neighbor 172.16.2.220 remote-as 65135
 neighbor 172.16.2.236 remote-as 65136
 neighbor 172.16.2.252 remote-as 65137
!
line vty
