
!
hostname leaf_router_0_5
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65205
 bgp router-id 172.16.1.11
 no bgp ebgp-requires-policy
 network 10.0.5.0/24
 neighbor 172.16.1.10 remote-as 65100
 neighbor 172.16.1.26 remote-as 65101
 neighbor 172.16.1.42 remote-as 65102
 neighbor 172.16.1.58 remote-as 65103
 neighbor 172.16.1.74 remote-as 65104
 neighbor 172.16.1.90 remote-as 65105
 neighbor 172.16.1.106 remote-as 65106
 neighbor 172.16.1.122 remote-as 65107
!
line vty
