
!
hostname spine_router_3_1
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65131
 bgp router-id 172.16.0.27
 bgp bestpath as-path multipath-relax
 maximum-paths 32
 no bgp ebgp-requires-policy
  neighbor 172.16.0.26 remote-as 65000
 neighbor 172.16.0.58 remote-as 65000
 neighbor 172.16.0.90 remote-as 65000
 neighbor 172.16.0.122 remote-as 65000
 neighbor 172.16.1.81 remote-as 65230
 neighbor 172.16.1.83 remote-as 65231
 neighbor 172.16.1.85 remote-as 65232
 neighbor 172.16.1.87 remote-as 65233
 neighbor 172.16.1.89 remote-as 65234
 neighbor 172.16.1.91 remote-as 65235
 neighbor 172.16.1.93 remote-as 65236
 neighbor 172.16.1.95 remote-as 65237
!
line vty
