LAB_NAME="campus_dhcp"
LAB_DESCRIPTION="OSPF Enterprise DHCP"

router_core_1[0]="router_core_1_router_core_2"
router_core_1[1]="router_core_1_router_core_3"
router_core_1[2]="router_core_1_router_dist_1_1"
router_core_1[image]="kathara/nika-frr"
router_core_1[cpus]=0.5
router_core_1[mem]="256m"

router_core_2[0]="router_core_1_router_core_2"
router_core_2[1]="router_core_2_router_core_3"
router_core_2[2]="router_core_2_router_dist_2_1"
router_core_2[image]="kathara/nika-frr"
router_core_2[cpus]=0.5
router_core_2[mem]="256m"

router_core_3[0]="router_core_1_router_core_3"
router_core_3[1]="router_core_2_router_core_3"
router_core_3[2]="router_core_3_server_access_router"
router_core_3[image]="kathara/nika-frr"
router_core_3[cpus]=0.5
router_core_3[mem]="256m"

router_dist_1_1[0]="router_core_1_router_dist_1_1"
router_dist_1_1[1]="router_dist_1_1_switch_access_1_1_1"
router_dist_1_1[image]="kathara/nika-frr"
router_dist_1_1[cpus]=0.5
router_dist_1_1[mem]="256m"

router_dist_2_1[0]="router_core_2_router_dist_2_1"
router_dist_2_1[1]="router_dist_2_1_switch_access_2_1_1"
router_dist_2_1[image]="kathara/nika-frr"
router_dist_2_1[cpus]=0.5
router_dist_2_1[mem]="256m"

server_access_router[0]="server_access_router_dns_server"
server_access_router[1]="server_access_router_web_server_0"
server_access_router[2]="server_access_router_web_server_1"
server_access_router[3]="server_access_router_web_server_2"
server_access_router[4]="server_access_router_web_server_3"
server_access_router[5]="server_access_router_load_balancer"
server_access_router[6]="server_access_router_dhcp_server"
server_access_router[7]="router_core_3_server_access_router"
server_access_router[image]="kathara/nika-frr"
server_access_router[cpus]=0.5
server_access_router[mem]="256m"

switch_access_1_1_1[0]="router_dist_1_1_switch_access_1_1_1"
switch_access_1_1_1[1]="switch_access_1_1_1_host_1_1_1_1"
switch_access_1_1_1[image]="kathara/nika-base"
switch_access_1_1_1[cpus]=0.5
switch_access_1_1_1[mem]="256m"

switch_access_2_1_1[0]="router_dist_2_1_switch_access_2_1_1"
switch_access_2_1_1[1]="switch_access_2_1_1_host_2_1_1_1"
switch_access_2_1_1[image]="kathara/nika-base"
switch_access_2_1_1[cpus]=0.5
switch_access_2_1_1[mem]="256m"

host_1_1_1_1[0]="switch_access_1_1_1_host_1_1_1_1"
host_1_1_1_1[image]="kathara/nika-base"
host_1_1_1_1[cpus]=0.5
host_1_1_1_1[mem]="256m"

host_2_1_1_1[0]="switch_access_2_1_1_host_2_1_1_1"
host_2_1_1_1[image]="kathara/nika-base"
host_2_1_1_1[cpus]=0.5
host_2_1_1_1[mem]="256m"

dns_server[0]="server_access_router_dns_server"
dns_server[image]="kathara/nika-base"
dns_server[cpus]=0.5
dns_server[mem]="256m"

web_server_0[0]="server_access_router_web_server_0"
web_server_0[image]="kathara/nika-base"
web_server_0[cpus]=0.5
web_server_0[mem]="256m"

web_server_1[0]="server_access_router_web_server_1"
web_server_1[image]="kathara/nika-base"
web_server_1[cpus]=0.5
web_server_1[mem]="256m"

web_server_2[0]="server_access_router_web_server_2"
web_server_2[image]="kathara/nika-base"
web_server_2[cpus]=0.5
web_server_2[mem]="256m"

web_server_3[0]="server_access_router_web_server_3"
web_server_3[image]="kathara/nika-base"
web_server_3[cpus]=0.5
web_server_3[mem]="256m"

load_balancer[0]="server_access_router_load_balancer"
load_balancer[1]="lb_backend_link"
load_balancer[image]="kathara/nika-nginx"
load_balancer[cpus]=0.5
load_balancer[mem]="256m"

dhcp_server[0]="server_access_router_dhcp_server"
dhcp_server[image]="kathara/nika-base"
dhcp_server[cpus]=0.5
dhcp_server[mem]="256m"

backend_web_0[0]="lb_backend_link"
backend_web_0[image]="kathara/nika-base"
backend_web_0[cpus]=0.5
backend_web_0[mem]="256m"

backend_web_1[0]="lb_backend_link"
backend_web_1[image]="kathara/nika-base"
backend_web_1[cpus]=0.5
backend_web_1[mem]="256m"

backend_web_2[0]="lb_backend_link"
backend_web_2[image]="kathara/nika-base"
backend_web_2[cpus]=0.5
backend_web_2[mem]="256m"
