
!
hostname leaf_router_1_5
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65215
 bgp router-id 172.16.1.139
 no bgp ebgp-requires-policy
 network 10.1.5.0/24
 neighbor 172.16.1.138 remote-as 65110
 neighbor 172.16.1.154 remote-as 65111
 neighbor 172.16.1.170 remote-as 65112
 neighbor 172.16.1.186 remote-as 65113
 neighbor 172.16.1.202 remote-as 65114
 neighbor 172.16.1.218 remote-as 65115
 neighbor 172.16.1.234 remote-as 65116
 neighbor 172.16.1.250 remote-as 65117
!
line vty
