LAB_NAME="sdn_clos"
LAB_DESCRIPTION="SDN Clos topology"

spine_1[0]="spine_1_leaf_1"
spine_1[1]="spine_1_leaf_2"
spine_1[2]="switch_controller"
spine_1[image]="kathara/sdn"
spine_1[cpus]=0.5
spine_1[mem]="256m"

leaf_1[0]="host_1_1_leaf_1"
leaf_1[1]="host_1_2_leaf_1"
leaf_1[2]="spine_1_leaf_1"
leaf_1[3]="switch_controller"
leaf_1[image]="kathara/sdn"
leaf_1[cpus]=0.5
leaf_1[mem]="256m"

leaf_2[0]="host_2_1_leaf_2"
leaf_2[1]="host_2_2_leaf_2"
leaf_2[2]="spine_1_leaf_2"
leaf_2[3]="switch_controller"
leaf_2[image]="kathara/sdn"
leaf_2[cpus]=0.5
leaf_2[mem]="256m"

host_1_1[0]="host_1_1_leaf_1"
host_1_1[image]="kathara/nika-base"
host_1_1[cpus]=0.5
host_1_1[mem]="256m"

host_1_2[0]="host_1_2_leaf_1"
host_1_2[image]="kathara/nika-base"
host_1_2[cpus]=0.5
host_1_2[mem]="256m"

host_2_1[0]="host_2_1_leaf_2"
host_2_1[image]="kathara/nika-base"
host_2_1[cpus]=0.5
host_2_1[mem]="256m"

host_2_2[0]="host_2_2_leaf_2"
host_2_2[image]="kathara/nika-base"
host_2_2[cpus]=0.5
host_2_2[mem]="256m"

controller[0]="switch_controller"
controller[image]="kathara/nika-ryu"
controller[cpus]=0.5
controller[mem]="256m"
controller[bridged]=true
