
!
hostname leaf_router_1_7
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65217
 bgp router-id 172.16.1.143
 no bgp ebgp-requires-policy
 network 10.1.7.0/24
 neighbor 172.16.1.142 remote-as 65110
 neighbor 172.16.1.158 remote-as 65111
 neighbor 172.16.1.174 remote-as 65112
 neighbor 172.16.1.190 remote-as 65113
 neighbor 172.16.1.206 remote-as 65114
 neighbor 172.16.1.222 remote-as 65115
 neighbor 172.16.1.238 remote-as 65116
 neighbor 172.16.1.254 remote-as 65117
!
line vty
