[Interface]
Address = 172.16.1.21/24
PrivateKey = gLRosEproY1ixtgHhBPmX/hXVYwszK3ZiIrk3BUWS34=

[Peer]
PublicKey = 7Qzb/rxgC9Mqo+AO7wcKRAfCim7Ph/05mgMhv1Gvnik=
Endpoint = 20.0.0.2:51820
AllowedIPs = 172.16.1.0/24