[Interface]
Address = 172.16.1.11/24
PrivateKey = 2E+/y66w99Jena8hyPDvd/neDVjTIC2kpvt4BZgi2HA=

[Peer]
PublicKey = 7Qzb/rxgC9Mqo+AO7wcKRAfCim7Ph/05mgMhv1Gvnik=
Endpoint = 20.0.0.2:51820
AllowedIPs = 172.16.1.0/24