LAB_NAME="p4_int"
LAB_DESCRIPTION="P4 INT - 2 hosts, 4 switches, 1 collector"

pc1[0]="A"
pc1[image]="kathara/base"
pc1[cpus]=0.5
pc1[mem]="256m"

pc2[0]="D"
pc2[image]="kathara/base"
pc2[cpus]=0.5
pc2[mem]="256m"

collector[0]="G"
collector[image]="kathara/nika-influxdb"
collector[cpus]=0.5
collector[mem]="256m"

spine1[0]="B"
spine1[1]="E"
spine1[image]="kathara/p4"
spine1[cpus]=0.5
spine1[mem]="256m"

spine2[0]="C"
spine2[1]="F"
spine2[image]="kathara/p4"
spine2[cpus]=0.5
spine2[mem]="256m"

leaf1[0]="A"
leaf1[1]="B"
leaf1[2]="C"
leaf1[image]="kathara/p4"
leaf1[cpus]=0.5
leaf1[mem]="256m"

leaf2[0]="D"
leaf2[1]="E"
leaf2[2]="F"
leaf2[3]="G"
leaf2[image]="kathara/p4"
leaf2[cpus]=0.5
leaf2[mem]="256m"
