
!
hostname leaf_router_3_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65233
 bgp router-id 172.16.2.135
 no bgp ebgp-requires-policy
 network 10.3.3.0/24
 neighbor 172.16.2.134 remote-as 65130
 neighbor 172.16.2.150 remote-as 65131
 neighbor 172.16.2.166 remote-as 65132
 neighbor 172.16.2.182 remote-as 65133
 neighbor 172.16.2.198 remote-as 65134
 neighbor 172.16.2.214 remote-as 65135
 neighbor 172.16.2.230 remote-as 65136
 neighbor 172.16.2.246 remote-as 65137
!
line vty
