
!
hostname leaf_router_3_0
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65230
 bgp router-id 172.16.2.129
 no bgp ebgp-requires-policy
 network 10.3.0.0/24
 neighbor 172.16.2.128 remote-as 65130
 neighbor 172.16.2.144 remote-as 65131
 neighbor 172.16.2.160 remote-as 65132
 neighbor 172.16.2.176 remote-as 65133
 neighbor 172.16.2.192 remote-as 65134
 neighbor 172.16.2.208 remote-as 65135
 neighbor 172.16.2.224 remote-as 65136
 neighbor 172.16.2.240 remote-as 65137
!
line vty
