
!
hostname leaf_router_3_5
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65235
 bgp router-id 172.16.2.139
 no bgp ebgp-requires-policy
 network 10.3.5.0/24
 neighbor 172.16.2.138 remote-as 65130
 neighbor 172.16.2.154 remote-as 65131
 neighbor 172.16.2.170 remote-as 65132
 neighbor 172.16.2.186 remote-as 65133
 neighbor 172.16.2.202 remote-as 65134
 neighbor 172.16.2.218 remote-as 65135
 neighbor 172.16.2.234 remote-as 65136
 neighbor 172.16.2.250 remote-as 65137
!
line vty
