
!
hostname spine_router_1_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65113
 bgp router-id 172.16.0.15
 bgp bestpath as-path multipath-relax
 maximum-paths 32
 no bgp ebgp-requires-policy
  neighbor 172.16.0.14 remote-as 65000
 neighbor 172.16.0.46 remote-as 65000
 neighbor 172.16.0.78 remote-as 65000
 neighbor 172.16.0.110 remote-as 65000
 neighbor 172.16.0.241 remote-as 65210
 neighbor 172.16.0.243 remote-as 65211
 neighbor 172.16.0.245 remote-as 65212
 neighbor 172.16.0.247 remote-as 65213
 neighbor 172.16.0.249 remote-as 65214
 neighbor 172.16.0.251 remote-as 65215
 neighbor 172.16.0.253 remote-as 65216
 neighbor 172.16.0.255 remote-as 65217
!
line vty
