
!
hostname spine_router_3_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65133
 bgp router-id 172.16.0.31
 bgp bestpath as-path multipath-relax
 maximum-paths 32
 no bgp ebgp-requires-policy
  neighbor 172.16.0.30 remote-as 65000
 neighbor 172.16.0.62 remote-as 65000
 neighbor 172.16.0.94 remote-as 65000
 neighbor 172.16.0.126 remote-as 65000
 neighbor 172.16.1.113 remote-as 65230
 neighbor 172.16.1.115 remote-as 65231
 neighbor 172.16.1.117 remote-as 65232
 neighbor 172.16.1.119 remote-as 65233
 neighbor 172.16.1.121 remote-as 65234
 neighbor 172.16.1.123 remote-as 65235
 neighbor 172.16.1.125 remote-as 65236
 neighbor 172.16.1.127 remote-as 65237
!
line vty
