
!
hostname leaf_router_1_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65213
 bgp router-id 172.16.1.135
 no bgp ebgp-requires-policy
 network 10.1.3.0/24
 neighbor 172.16.1.134 remote-as 65110
 neighbor 172.16.1.150 remote-as 65111
 neighbor 172.16.1.166 remote-as 65112
 neighbor 172.16.1.182 remote-as 65113
 neighbor 172.16.1.198 remote-as 65114
 neighbor 172.16.1.214 remote-as 65115
 neighbor 172.16.1.230 remote-as 65116
 neighbor 172.16.1.246 remote-as 65117
!
line vty
