
!
hostname leaf_router_3_2
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65232
 bgp router-id 172.16.2.133
 no bgp ebgp-requires-policy
 network 10.3.2.0/24
 neighbor 172.16.2.132 remote-as 65130
 neighbor 172.16.2.148 remote-as 65131
 neighbor 172.16.2.164 remote-as 65132
 neighbor 172.16.2.180 remote-as 65133
 neighbor 172.16.2.196 remote-as 65134
 neighbor 172.16.2.212 remote-as 65135
 neighbor 172.16.2.228 remote-as 65136
 neighbor 172.16.2.244 remote-as 65137
!
line vty
