
!
hostname leaf_router_0_3
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65203
 bgp router-id 172.16.1.7
 no bgp ebgp-requires-policy
 network 10.0.3.0/24
 neighbor 172.16.1.6 remote-as 65100
 neighbor 172.16.1.22 remote-as 65101
 neighbor 172.16.1.38 remote-as 65102
 neighbor 172.16.1.54 remote-as 65103
 neighbor 172.16.1.70 remote-as 65104
 neighbor 172.16.1.86 remote-as 65105
 neighbor 172.16.1.102 remote-as 65106
 neighbor 172.16.1.118 remote-as 65107
!
line vty
