
!
hostname leaf_router_0_4
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65204
 bgp router-id 172.16.1.9
 no bgp ebgp-requires-policy
 network 10.0.4.0/24
 neighbor 172.16.1.8 remote-as 65100
 neighbor 172.16.1.24 remote-as 65101
 neighbor 172.16.1.40 remote-as 65102
 neighbor 172.16.1.56 remote-as 65103
 neighbor 172.16.1.72 remote-as 65104
 neighbor 172.16.1.88 remote-as 65105
 neighbor 172.16.1.104 remote-as 65106
 neighbor 172.16.1.120 remote-as 65107
!
line vty
